[project]
name = "project-supabse-streamlit-modal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "modal>=1.1.4",
    "streamlit>=1.49.1",
    "supabase>=2.18.1",
]
